### ISSUE TITLE
Crash on custom rom

### ISSUE THREAD

**Issue by TheBolshe** [XEonAX/ANXCamera#33]
I tried v190 and v185. I just installed the camera. Whenever I install the framework, any app using a camera crashes whenever it tries to. I don't have the log rn but it was an ArrayOutOfBouds error

time: 1598569813668
msg: java.lang.UnsatisfiedLinkError: No implementation found for int com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(java. lang.String) (tried Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init and Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init_ _Ljava_lang_String_2)
stacktrace: java.lang.UnsatisfiedLinkError: No implementation found for int com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(java. lang.String) (tried Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init and Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init_ _Ljava_lang_String_2)
at com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(Nativ e Method)
at com.xiaomi.engine.MiCameraAlgo.init(Unknown Source:39)
at com.android.camera.LocalParallelService$LocalBinde r.<init>(Unknown Source:75)
at com.android.camera.LocalParallelService.onCreate(U nknown Source:30)
at android.app.ActivityThread.handleCreateService(Act ivityThread.java:3953)
at android.app.ActivityThread.access$1500(ActivityThr ead.java:219)
at android.app.ActivityThread$H.handleMessage(Activit yThread.java:1875)
at android.os.Handler.dispatchMessage(Handler.java:10 7)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.jav a:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsC aller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit .java:940)

Phone Redmi Note 8 Pro (begonia)
CrDroid 6.9 (https://forum.xda-developers.com/redmi-note-8-pro/development/rom-crdroid-6-x-t4124805)
Installed ANX with Magisk 20.4

**Comment by TheBolshe** [comment]
Here is the log when framework is installed

```


time: 1598575800433
msg: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
stacktrace: java.lang.RuntimeException: Unable to resume activity {org.lineageos.snap/com.android.camera.CameraLauncher}: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.android.camera.PhotoModule.initializeFocusManager(PhotoModule.java:2830)
	at com.android.camera.PhotoModule.onResumeBeforeSuper(PhotoModule.java:2598)
	at com.android.camera.CameraActivity.onResume(CameraActivity.java:1889)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
	at android.app.Activity.performResume(Activity.java:7958)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
	... 11 more
```

**Comment by MCEventHorizon** [comment]
Same thing, using begonia with Resurrection Remix OS.

**Comment by XEonAX** [comment]
Can you try disabling parallel process and mialgoengine via ANX Camera Pro?

**Comment by MCEventHorizon** [comment]
Still crashing.

**Comment by Stimmenhotel** [comment]
Happening for me too.

Using latest RROS 8.6.5 Android 10
Was working before on 8.5.6 with v185.
Tried 184 and 185.

Disabling parallel process and mialgoengine haven't changed the crashing or the error message:
https://del.dog/yfillomerr
https://del.dog/toxyttojum.txt

**Comment by firebird11** [comment]
did anyone found a solution to this ?

**Comment by VergeDX** [comment]
@XEonAX 
Same issues here, RR 8.6.7 phoenix. Any log needed...? I'm willing to help.

**Comment by XEonAX** [comment]
If anybody knows how to fix, suggestions are welcome

**Comment by Stimmenhotel** [comment]
Today I tried using the rootless TWRP version 184 by hsgod02 and nuub1k (Check #anx_rootless of RROS Channel for Mi 9t Pro/K20 Pro == https://t.me/rr_raphael) and it is working. (May crash the first starts, just open it again)

That said, I haven't tested 184 Magisk version since 8.6.7 update... So if anyone still can't use ANX, check 184 again and if still not working, go for the rootless version.

**Comment by VergeDX** [comment]
I also found the bug report on [eu MIUI](https://xiaomi.eu/community/threads/help-10-ultra-how-to-replace-eu-rom-camera-with-stock-chinese-camera-on-weekly-roms.58301/) & [crDroid](https://forum.xda-developers.com/t/rom-cfw-10-crdroid-6-x-begonia-begoniain-official-antibrick.4124805/page-5), seems this is a common issues...  
I guess this maybe a vendor issue.

**Comment by toteto** [comment]
Having the same issues

```
time: 1614639201331
msg: java.lang.UnsatisfiedLinkError: No implementation found for int com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(java.lang.String) (tried Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init and Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init__Ljava_lang_String_2)
stacktrace: java.lang.UnsatisfiedLinkError: No implementation found for int com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(java.lang.String) (tried Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init and Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init__Ljava_lang_String_2)
	at com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(Native Method)
	at com.xiaomi.engine.MiCameraAlgo.init(Unknown Source:39)
	at com.android.camera.LocalParallelService$LocalBinder.<init>(Unknown Source:75)
	at com.android.camera.LocalParallelService.onCreate(Unknown Source:30)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4186)
	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by XEonAX** [comment]
> 
> 
> Having the same issues with v185 and Android 11 with Evolution X
> 
> ```
> time: 1614639201331
> msg: java.lang.UnsatisfiedLinkError: No implementation found for int com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(java.lang.String) (tried Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init and Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init__Ljava_lang_String_2)
> stacktrace: java.lang.UnsatisfiedLinkError: No implementation found for int com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(java.lang.String) (tried Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init and Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init__Ljava_lang_String_2)
> 	at com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(Native Method)
> 	at com.xiaomi.engine.MiCameraAlgo.init(Unknown Source:39)
> 	at com.android.camera.LocalParallelService$LocalBinder.<init>(Unknown Source:75)
> 	at com.android.camera.LocalParallelService.onCreate(Unknown Source:30)
> 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4186)
> 	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:223)
> 	at android.app.ActivityThread.main(ActivityThread.java:7661)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> ```

Can you try disabling parallel process and mialgoengine via ANX Camera Pro?

**Comment by alphatoasterous** [comment]
Got the same issue on Xiaomi Redmi Note 9s (curtana/miatoll) with v190 on Resurrection Remix 8.6.5 by TeamMEX.

```
time: 1623167980883
msg: java.lang.UnsatisfiedLinkError: No implementation found for int com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(java.lang.String) (tried Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init and Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init__Ljava_lang_String_2)
stacktrace: java.lang.UnsatisfiedLinkError: No implementation found for int com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(java.lang.String) (tried Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init and Java_com_xiaomi_engine_MiCamAlgoInterfaceJNI_init__Ljava_lang_String_2)
	at com.xiaomi.engine.MiCamAlgoInterfaceJNI.init(Native Method)
	at com.xiaomi.engine.MiCameraAlgo.init(Unknown Source:39)
	at com.android.camera.LocalParallelService$LocalBinder.<init>(Unknown Source:75)
	at com.android.camera.LocalParallelService.onCreate(Unknown Source:30)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3954)
	at android.app.ActivityThread.access$1500(ActivityThread.java:220)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

And I actually managed to fix it by giving it permissions to camera, storage, location and microphone in App Info. I wonder if it really fixes it on other devices.

Used magisk modules:
ANX48MPFix Q 181
ANXCamera 190
ANXCamera Framework 190
ANXCamera Provider 190
ANXCamera Bootloop Fix 190
